project:
  type: book
  output-dir: docs

lang: pt-BR

book:
  title: "OSUBH Capacita"
  subtitle: "Grupo de Estudos e Capacitação do Observatório de Saúde Urbana de Belo Horizonte (OSUBH)"
  chapters:
    - index.qmd
    - 01 - R.qmd
    - 02 - Positron.qmd
    - 03 - Introdução em R.qmd
    - 04 - GitHub.qmd
    - 05 - Boas práticas de programação.qmd
    - 06 - Quarto.qmd

format:
  html:
    theme: cosmo
    page-layout: full
    toc: true
    number-sections: false
    code-fold: false
  pdf:
    documentclass: scrreprt

execute:
  warning: false
  message: false
